Add `json` extension to networks import
maticnetwork/static pull request #51
Opened 2021-05-16 17:54 UTC by GladOSkar

As workaround for TypeScript compilers since they can't resolve JSON files without an extension.

See microsoft/TypeScript#24357

2021-06-15 18:17 UTC, GladOSkar commented
Soo is this project dead? @arthcp

2021-06-20 05:21 UTC, tota999 requested changes
Ya

2021-06-22 06:20 UTC, arthcp commented
@rahuldamodar94 @itzmeanjan Can you guys take a look?

2021-07-20 21:29 UTC, GladOSkar commented
Bump

2021-08-18 10:35 UTC, rahuldamodar94 approved these changes

2021-08-18 10:35 UTC, merged

2021-08-18 18:10 UTC, GladOSkar commented
Thanks! :+1: